events {}

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /env {
            default_type text/plain;
            return 200 "$STUDENT_NAME";
        }
    }
}
